ITrack/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITrack.Models;

namespace ITrack.Controllers
{
    public class CompaniesController : Controller
    {
        private ITrackDB db = new ITrackDB();

        // GET: Companies
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(db.Companies.ToList());
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Companies companies = db.Companies.Find(id);
            if (companies == null)
            {
                return HttpNotFound();
            }
            return View(companies);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }

        public ActionResult CreateNewEmployee()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompaniesId,CompanyName")] Companies companies)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(companies);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(companies);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Companies companies = db.Companies.Find(id);
            if (companies == null)
            {
                return HttpNotFound();
            }
            return View(companies);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompaniesId,CompanyName")] Companies companies)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companies).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(companies);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Companies companies = db.Companies.Find(id);
            if (companies == null)
            {
                return HttpNotFound();
            }
            return View(companies);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Companies companies = db.Companies.Find(id);
            db.Companies.Remove(companies);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITrack/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITrack.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace ITrack.Controllers
{
    public class TicketsController : Controller
    {
        private ITrackDB db = new ITrackDB();
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Tickets
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var UserID = User.Identity.GetUserId();
                string userCompany = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(UserID).Company;
                ViewBag.CompanyName = userCompany;
                List<Tickets> CompanyTickets = new List<Tickets>();
                return View(db.Tickets.ToList());
            }
            else
            {
                return Redirect("~/Account/Login");
            }
        }

        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tickets tickets = db.Tickets.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            var UserID = User.Identity.GetUserId();
            string userCompany = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(UserID).Company;

            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CompanyName = userCompany;
                return View();
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }

        public ActionResult ViewOpenTickets()
        {
            ViewResult result;
            if (User.Identity.IsAuthenticated)
            {
                var UserID = User.Identity.GetUserId();
                List<Tickets> listOfTickets = new List<Tickets>();
               
                string userCompany = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(UserID).Company;
                foreach (var ticket in db.Tickets)
                {
                    if (ticket.Company == userCompany)
                    {
                        listOfTickets.Add(ticket);
                    }
                    else
                    {
                        result = View();
                    }
                }
                result = View(listOfTickets);
                return result;
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Client,Company,Details,TimeRequest,Priority,Employee,Completed,TimeCompleted")] Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                db.Tickets.Add(tickets);
                db.SaveChanges();
                return RedirectToAction("ViewOpenTickets");
            }

            return View(tickets);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tickets tickets = db.Tickets.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Client,Company,Details,TimeRequest,Priority,Employee,Completed,TimeCompleted")] Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tickets).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewOpenTickets");
            }
            return View(tickets);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tickets tickets = db.Tickets.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tickets tickets = db.Tickets.Find(id);
            db.Tickets.Remove(tickets);
            db.SaveChanges();
            return RedirectToAction("ViewOpenTickets");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITrack/Controllers/TrackersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITrack.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Security;
using System.Threading.Tasks;


namespace ITrack.Controllers
{
    public class TrackersController : Controller
    {
        private ITrackDB db = new ITrackDB();
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Trackers
        public ActionResult Index()
        {
            ViewResult result;
            if (User.Identity.IsAuthenticated)
            {
                var UserID = User.Identity.GetUserId();
                List<Tracker> listOfTrackers = new List<Tracker>();

                string userCompany = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(UserID).Company;
                foreach (var tracks in db.Trackers)
                {
                    if (tracks.Company == userCompany)
                    {
                        listOfTrackers.Add(tracks);
                    }
                    else
                    {
                        result = View();
                    }
                }
                result = View(listOfTrackers);
                return result;
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }
        
        // GET: Trackers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tracker tracker = db.Trackers.Find(id);
            if (tracker == null)
            {
                return HttpNotFound();
            }
            return View(tracker);
        }

        // GET: Trackers/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                var UserID = User.Identity.GetUserId();
                string userCompany = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(UserID).Company;
                ApplicationDbContext context = new ApplicationDbContext();
                List<ApplicationUser> AllDBUsers = context.Users.ToList();
                List<ApplicationUser> companyUsers = new List<ApplicationUser>();
                foreach (var user in AllDBUsers)
                {
                    if(user.Company == userCompany)
                    {
                        companyUsers.Add(user);
                    }
                }
                ViewBag.CompanyName = userCompany;
                ViewBag.UserList = companyUsers;
                return View();
            }

            else
            {
                return Redirect("~/Account/Login");
            }
        }


        //public ActionResult ShowAllNames()
        //{
        //    var users = Membership.GetAllUsers();

        //    return View(users);
        //}


        // POST: Trackers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TimeOut,TicketID,Details,Location,Employee,ReturnDate,Company")] Tracker tracker)
        {
            if (ModelState.IsValid)
            {
                db.Trackers.Add(tracker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tracker);
        }

        
        // GET: Trackers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tracker tracker = db.Trackers.Find(id);
            if (tracker == null)
            {
                return HttpNotFound();
            }
            return View(tracker);
        }

        public MembershipUserCollection ShowAllUsers()
        {
            var users = Membership.GetAllUsers();
            //SelectList listOfUsers = new SelectList(users);
            return users; 
        }

        // POST: Trackers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TimeOut,TicketID,Details,Location,Employee,ReturnDate,Company")] Tracker tracker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tracker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tracker);
        }

        // GET: Trackers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tracker tracker = db.Trackers.Find(id);
            if (tracker == null)
            {
                return HttpNotFound();
            }
            return View(tracker);
        }

        // POST: Trackers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tracker tracker = db.Trackers.Find(id);
            db.Trackers.Remove(tracker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITrack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ITrack*</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ITrack*", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
                <ul class="nav navbar-nav">
                   @if (User.IsInRole("MasterAdmin"))
                   {
                     <li class="dropdown">
                       
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Company <span class="caret"></span></a>
                        <ul class="dropdown-menu">                           
                                <li>@Html.ActionLink("Company Index", "Index", "Companies")</li>
                                <li>@Html.ActionLink("Create", "Create", "Companies")</li>                           
                        </ul>
                    </li>
                    }
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Inventory <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Inventory Index", "Index", "Inventories")</li>
                            @if (User.IsInRole("MasterAdmin")||User.IsInRole("CompanyAdmin")) 
                            {
                            <li>@Html.ActionLink("Create", "Create", "Inventories")</li>
                            }
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ticket <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Ticket Index", "Index", "Tickets")</li>
                            @if (User.IsInRole("MasterAdmin") || User.IsInRole("CompanyAdmin"))
                            {
                                <li>@Html.ActionLink("Create", "Create", "Tickets")</li>
                            }
                            
                            <li>@Html.ActionLink("View Open Tickets", "ViewOpenTickets", "Tickets")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tracker <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Tracker Index", "Index", "Trackers")</li>

                            @if (User.IsInRole("MasterAdmin") || User.IsInRole("CompanyAdmin"))
                            {
                                <li>@Html.ActionLink("Create", "Create", "Trackers")</li>
                            }
                        </ul>
                    </li>

                    @if (User.IsInRole("MasterAdmin") || User.IsInRole("CompanyAdmin"))
                    {
                        <li>@Html.ActionLink("Change Employee Role", "Index", "RoleAssignment")</li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ITrack<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>